services:
  my_app:
    depends_on:
      - postgres
    image: my_app
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/my_db
    networks:
      - my_net
  postgres:
    image: postgres:15.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - my_net
networks:
  my_net:
    driver: bridge